#!/bin/bash
# BrieFS + xfstests VM setup. Run inside the dev VM (e.g. via
# `vagrant ssh -c 'sudo bash /vagrant/tests/xfstests/setup-vm.sh [xfstests-dir]'`).
#
# This is a one-shot (re-runnable) setup for the BrieFS side of xfstests phase 1:
#   1. build briefs_fs.ko in the VM (against the VM kernel headers) and install
#      it into /lib/modules/$(uname -r) + depmod, so `modprobe fs-briefs` works
#      and `mount -t briefs` auto-loads it (MODULE_ALIAS_FS("briefs")).
#   2. symlink mkfs.briefs / fsck.briefs into /usr/sbin so the util-linux
#      `fsck -t briefs` / `mkfs -t briefs` front-ends find them.
#   3. create two loop-backed image files for TEST_DEV / SCRATCH_DEV and the
#      mount points.
#   4. smoke-test: modprobe fs-briefs, mount, O_DIRECT rejected, fsck -n.
#
# Argument (optional): the xfstests checkout dir inside the VM (defaults to
# /xfstests, or whatever you synced the host /home/jeremy/src/xfstests-dev to).
set -euo pipefail

XFSTESTS_DIR="${1:-/xfstests}"
BRIEFS_SRC="/vagrant"
IMG_DIR="/var/lib/xfstests-briefs"
TEST_IMG="$IMG_DIR/test.img"
SCRATCH_IMG="$IMG_DIR/scratch.img"
TEST_MNT="/mnt/briefs-test"
SCRATCH_MNT="/mnt/briefs-scratch"
IMG_SIZE_MB=4096

if [ "$(id -u)" -ne 0 ]; then
	echo "must run as root (try: sudo bash $0)" >&2
	exit 1
fi

echo "=== building briefs_fs.ko in the VM ==="
cd "$BRIEFS_SRC"
make clean >/dev/null 2>&1 || true
make -j"$(nproc)" 2>&1 | tail -5
test -f briefs_fs.ko || { echo "build failed: no briefs_fs.ko" >&2; exit 1; }

echo "=== installing module into $(uname -r) module tree ==="
MODDIR="/lib/modules/$(uname -r)/extra/briefs"
mkdir -p "$MODDIR"
rmmod briefs_fs 2>/dev/null || true
install -m 644 briefs_fs.ko "$MODDIR/briefs_fs.ko"
depmod -a
echo "  installed: $MODDIR/briefs_fs.ko"
if ! modinfo briefs_fs >/dev/null 2>&1; then
	echo "  modinfo cannot find briefs_fs" >&2; exit 1
fi
echo "  alias: $(modinfo briefs_fs 2>/dev/null | grep -E 'alias:|filename:' | head -3 | tr '\n' ' ')"

echo "=== symlinking mkfs.briefs / fsck.briefs into /usr/sbin ==="
ln -sf /go/bin/mkfs.briefs /usr/sbin/mkfs.briefs
ln -sf /go/bin/fsck.briefs /usr/sbin/fsck.briefs
# Ensure the Go tools exist (built on the host, shared via /go).
for t in mkfs.briefs fsck.briefs; do
	if ! [ -x "/go/bin/$t" ]; then
		echo "  WARNING: /go/bin/$t missing (build briefs-utils on the host)" >&2
	fi
done

echo "=== creating loop-backed test/scratch devices ==="
mkdir -p "$IMG_DIR" "$TEST_MNT" "$SCRATCH_MNT"
# Detach any old loops pointing at our images.
for img in "$TEST_IMG" "$SCRATCH_IMG"; do
	lo="$(losetup -j "$img" 2>/dev/null | cut -d: -f1 || true)"
	[ -n "$lo" ] && losetup -d "$lo" 2>/dev/null || true
done
# (Re)create sparse images.
truncate -s "${IMG_SIZE_MB}M" "$TEST_IMG"
truncate -s "${IMG_SIZE_MB}M" "$SCRATCH_IMG"
TEST_LOOP="$(losetup -f --show "$TEST_IMG")"
SCRATCH_LOOP="$(losetup -f --show "$SCRATCH_IMG")"
echo "  TEST_DEV=$TEST_LOOP  (-> $TEST_IMG)"
echo "  SCRATCH_DEV=$SCRATCH_LOOP  (-> $SCRATCH_IMG)"

echo "=== writing resolved config to $XFSTESTS_DIR/configs/briefs.config ==="
if [ -d "$XFSTESTS_DIR/configs" ]; then
	cat > "$XFSTESTS_DIR/configs/briefs.config" <<EOF
# Auto-generated by briefs setup-vm.sh (loops may change between runs).
[briefs]
export FSTYP=briefs
export TEST_DIR=$TEST_MNT
export SCRATCH_MNT=$SCRATCH_MNT
export TEST_DEV=$TEST_LOOP
export SCRATCH_DEV=$SCRATCH_LOOP
export MKFS_PROG=/go/bin/mkfs.briefs
export FSCK_PROG=/go/bin/fsck.briefs
export MKFS_OPTIONS=""
export MOUNT_OPTIONS=""
export FSCK_OPTIONS="-n"
EOF
	echo "  wrote $XFSTESTS_DIR/configs/briefs.config"
else
	echo "  WARNING: $XFSTESTS_DIR/configs not found; skip config rewrite" >&2
fi

echo "=== smoke test ==="
modprobe -r fs-briefs 2>/dev/null || true
modprobe fs-briefs && echo "  PASS: modprobe fs-briefs" || { echo "  FAIL: modprobe fs-briefs" >&2; exit 1; }
/go/bin/mkfs.briefs "$TEST_LOOP" >/dev/null 2>&1 && echo "  PASS: mkfs" || { echo "  FAIL: mkfs" >&2; exit 1; }
mount -t briefs "$TEST_LOOP" "$TEST_MNT" && echo "  PASS: mount -t briefs" || { echo "  FAIL: mount" >&2; exit 1; }
# O_DIRECT must be rejected at open (-EINVAL) so xfstests _require_odirect skips.
if xfs_io -d -f -c "pwrite -S 0x55 0 4k" "$TEST_MNT/odirect_test" >/dev/null 2>&1; then
	echo "  WARN: O_DIRECT open unexpectedly succeeded (reject patch not active?)" >&2
else
	echo "  PASS: O_DIRECT rejected at open (xfs_io -d failed as expected)"
fi
rm -f "$TEST_MNT/odirect_test"
umount "$TEST_MNT"
/go/bin/fsck.briefs -n "$TEST_LOOP" >/dev/null 2>&1 && echo "  PASS: fsck -n (read-only)" || { echo "  FAIL: fsck -n" >&2; exit 1; }

echo
echo "=== setup complete ==="
echo "Next: from $XFSTESTS_DIR run:"
echo "  HOST_OPTIONS=configs/briefs.config ./check -s briefs -g generic"
echo "(xfstests deps must be installed: apt-get install xfsprogs attr acl ...)"